import { Match, WatchParty, Team, Venue } from "@/types";

export const MOCK_TEAMS: Team[] = [
  { id: "t1", name: "Argentina", code: "ARG", flag: "🇦🇷", group: "A" },
  { id: "t2", name: "France", code: "FRA", flag: "🇫🇷", group: "A" },
  { id: "t3", name: "Brazil", code: "BRA", flag: "🇧🇷", group: "B" },
  { id: "t4", name: "England", code: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", group: "B" },
  { id: "t5", name: "Germany", code: "GER", flag: "🇩🇪", group: "C" },
  { id: "t6", name: "Spain", code: "ESP", flag: "🇪🇸", group: "C" },
  { id: "t7", name: "Portugal", code: "POR", flag: "🇵🇹", group: "D" },
  { id: "t8", name: "Netherlands", code: "NED", flag: "🇳🇱", group: "D" },
  { id: "t9", name: "USA", code: "USA", flag: "🇺🇸", group: "E" },
  { id: "t10", name: "Mexico", code: "MEX", flag: "🇲🇽", group: "E" },
  { id: "t11", name: "Japan", code: "JPN", flag: "🇯🇵", group: "F" },
  { id: "t12", name: "Morocco", code: "MAR", flag: "🇲🇦", group: "F" },
];

const now = new Date();
const hoursFromNow = (h: number) => new Date(now.getTime() + h * 3600 * 1000);

export const MOCK_MATCHES: Match[] = [
  {
    id: "m1",
    homeTeam: MOCK_TEAMS[0],
    awayTeam: MOCK_TEAMS[1],
    kickoffTime: hoursFromNow(2),
    venue: "Lusail Iconic Stadium",
    city: "Lusail",
    country: "Qatar",
    stage: "Group Stage",
    status: "UPCOMING",
    homeScore: null,
    awayScore: null,
    watchPartiesCount: 47,
  },
  {
    id: "m2",
    homeTeam: MOCK_TEAMS[2],
    awayTeam: MOCK_TEAMS[3],
    kickoffTime: hoursFromNow(5),
    venue: "Al Bayt Stadium",
    city: "Al Khor",
    country: "Qatar",
    stage: "Group Stage",
    status: "UPCOMING",
    homeScore: null,
    awayScore: null,
    watchPartiesCount: 63,
  },
  {
    id: "m3",
    homeTeam: MOCK_TEAMS[4],
    awayTeam: MOCK_TEAMS[5],
    kickoffTime: hoursFromNow(-1),
    venue: "Education City Stadium",
    city: "Al Rayyan",
    country: "Qatar",
    stage: "Group Stage",
    status: "LIVE",
    homeScore: 1,
    awayScore: 2,
    watchPartiesCount: 89,
  },
  {
    id: "m4",
    homeTeam: MOCK_TEAMS[6],
    awayTeam: MOCK_TEAMS[7],
    kickoffTime: hoursFromNow(26),
    venue: "Stadium 974",
    city: "Doha",
    country: "Qatar",
    stage: "Round of 16",
    status: "UPCOMING",
    homeScore: null,
    awayScore: null,
    watchPartiesCount: 31,
  },
  {
    id: "m5",
    homeTeam: MOCK_TEAMS[8],
    awayTeam: MOCK_TEAMS[9],
    kickoffTime: hoursFromNow(50),
    venue: "Al Thumama Stadium",
    city: "Doha",
    country: "Qatar",
    stage: "Quarter Final",
    status: "UPCOMING",
    homeScore: null,
    awayScore: null,
    watchPartiesCount: 22,
  },
  {
    id: "m6",
    homeTeam: MOCK_TEAMS[10],
    awayTeam: MOCK_TEAMS[11],
    kickoffTime: hoursFromNow(-26),
    venue: "Ahmad Bin Ali Stadium",
    city: "Al Rayyan",
    country: "Qatar",
    stage: "Group Stage",
    status: "FINISHED",
    homeScore: 2,
    awayScore: 1,
    watchPartiesCount: 15,
  },
];

export const MOCK_VENUES: Venue[] = [
  {
    id: "v1",
    name: "The Argentinian Corner",
    address: "123 Fan Street",
    city: "Buenos Aires",
    country: "Argentina",
    latitude: -34.6037,
    longitude: -58.3816,
    type: "SPORTS_BAR",
    capacity: 200,
    imageUrl: null,
    atmosphereRating: 4.8,
    safetyRating: 4.5,
  },
  {
    id: "v2",
    name: "Samba Lounge",
    address: "456 Copacabana Ave",
    city: "Rio de Janeiro",
    country: "Brazil",
    latitude: -22.9068,
    longitude: -43.1729,
    type: "SPORTS_BAR",
    capacity: 150,
    imageUrl: null,
    atmosphereRating: 4.9,
    safetyRating: 4.2,
  },
];

export const MOCK_WATCH_PARTIES: WatchParty[] = [
  {
    id: "wp1",
    title: "Argentina Mega Watch Party 🇦🇷",
    description:
      "Join 200+ Argentina fans for the biggest watch party in the city! Full bar, food, live DJ before kickoff.",
    match: MOCK_MATCHES[0],
    venue: MOCK_VENUES[0],
    creator: { id: "u1", name: "Carlos Rivera", image: null, username: "carlosriva" },
    latitude: 40.7128,
    longitude: -74.006,
    address: "Times Square Sports Bar, New York",
    vibe: "PARTY",
    isPublic: true,
    maxAttendees: 300,
    currentAttendees: 187,
    safetyLevel: "SAFE",
    aiSummary:
      "High-energy Argentina fan crowd expected with 200+ attendees. Perfect for die-hard fans and first-timers alike. Festive atmosphere with live music, face painting, and authentic food.",
    crowdNationalities: { Argentina: 60, USA: 20, Brazil: 8, Uruguay: 7, Other: 5 },
    popularityScore: 9.2,
    imageUrl: null,
    startTime: hoursFromNow(1),
    endTime: hoursFromNow(4),
    createdAt: new Date(),
  },
  {
    id: "wp2",
    title: "Brazil Fans — Samba Night 🇧🇷",
    description:
      "Chill vibes, caiprinhas, and pure Samba energy. Watch Brazil dominate with fellow fans!",
    match: MOCK_MATCHES[1],
    venue: null,
    creator: { id: "u2", name: "Ana Lima", image: null, username: "analima" },
    latitude: 40.7484,
    longitude: -73.9967,
    address: "Midtown Manhattan, New York",
    vibe: "CHILL",
    isPublic: true,
    maxAttendees: 80,
    currentAttendees: 52,
    safetyLevel: "SAFE",
    aiSummary:
      "Intimate Brazil fan gathering with chill vibes. Great for meeting locals and expats. Known for incredible atmosphere and friendly crowd.",
    crowdNationalities: { Brazil: 70, Portugal: 10, Colombia: 8, USA: 7, Other: 5 },
    popularityScore: 8.4,
    imageUrl: null,
    startTime: hoursFromNow(4),
    endTime: hoursFromNow(7),
    createdAt: new Date(),
  },
  {
    id: "wp3",
    title: "Germany vs Spain — Tactical Watch 🇩🇪🇪🇸",
    description:
      "For the true football nerds. Live commentary, tactical analysis, post-match discussion.",
    match: MOCK_MATCHES[2],
    venue: null,
    creator: { id: "u3", name: "Max Schmidt", image: null, username: "maxschmidt" },
    latitude: 40.7282,
    longitude: -73.7949,
    address: "Queens, New York",
    vibe: "HARDCORE",
    isPublic: true,
    maxAttendees: 50,
    currentAttendees: 34,
    safetyLevel: "SAFE",
    aiSummary:
      "Hardcore football fans watching a classic European rivalry. Expect passionate debates, expert analysis, and intense crowd reactions. Safety rated excellent.",
    crowdNationalities: { Germany: 35, Spain: 35, Netherlands: 10, England: 10, Other: 10 },
    popularityScore: 7.8,
    imageUrl: null,
    startTime: hoursFromNow(-1),
    endTime: hoursFromNow(2),
    createdAt: new Date(),
  },
  {
    id: "wp4",
    title: "Family Football Fun 👨‍👩‍👧‍👦",
    description:
      "Kid-friendly watch party! Games, activities for children, and great food. Everyone welcome!",
    match: MOCK_MATCHES[0],
    venue: null,
    creator: { id: "u4", name: "Sarah Johnson", image: null, username: "sarahj" },
    latitude: 40.6892,
    longitude: -74.0445,
    address: "Brooklyn, New York",
    vibe: "FAMILY",
    isPublic: true,
    maxAttendees: 60,
    currentAttendees: 28,
    safetyLevel: "SAFE",
    aiSummary:
      "Perfect family-friendly environment with activities for all ages. Zero alcohol required. Great for introducing kids to the beautiful game.",
    crowdNationalities: { USA: 50, Argentina: 20, Mexico: 15, Other: 15 },
    popularityScore: 7.1,
    imageUrl: null,
    startTime: hoursFromNow(1.5),
    endTime: hoursFromNow(4.5),
    createdAt: new Date(),
  },
  {
    id: "wp5",
    title: "International Fan Zone 🌍",
    description:
      "Meet fans from 30+ countries! The most diverse watch party in the city. Translation available.",
    match: MOCK_MATCHES[3],
    venue: null,
    creator: { id: "u5", name: "Yuki Tanaka", image: null, username: "yukitanaka" },
    latitude: 40.7614,
    longitude: -73.9776,
    address: "Midtown East, New York",
    vibe: "INTERNATIONAL",
    isPublic: true,
    maxAttendees: 200,
    currentAttendees: 143,
    safetyLevel: "SAFE",
    aiSummary:
      "The most diverse watch party in the city with fans from 30+ countries. AI translation available. Perfect for solo travelers and international visitors.",
    crowdNationalities: {
      Japan: 15,
      Morocco: 12,
      USA: 10,
      France: 8,
      Brazil: 7,
      Germany: 6,
      Other: 42,
    },
    popularityScore: 9.5,
    imageUrl: null,
    startTime: hoursFromNow(25),
    endTime: hoursFromNow(28),
    createdAt: new Date(),
  },
];

export const COUNTRIES = [
  "Argentina", "Australia", "Belgium", "Brazil", "Cameroon", "Canada",
  "Costa Rica", "Croatia", "Denmark", "Ecuador", "England", "France",
  "Germany", "Ghana", "Iran", "Japan", "Mexico", "Morocco", "Netherlands",
  "Poland", "Portugal", "Qatar", "Saudi Arabia", "Senegal", "Serbia",
  "South Korea", "Spain", "Switzerland", "Tunisia", "USA", "Uruguay", "Wales",
];

export const LANGUAGES = [
  "English", "Spanish", "Portuguese", "French", "German", "Arabic",
  "Japanese", "Korean", "Italian", "Dutch", "Polish", "Turkish",
  "Russian", "Mandarin", "Hindi", "Swahili",
];

export const VIBE_TAGS = [
  { value: "hardcore_fan", label: "Hardcore Fan", emoji: "⚽" },
  { value: "casual_fan", label: "Casual Fan", emoji: "😎" },
  { value: "party_crowd", label: "Party Crowd", emoji: "🎉" },
  { value: "chill_viewer", label: "Chill Viewer", emoji: "🛋️" },
  { value: "international_traveler", label: "International Traveler", emoji: "✈️" },
  { value: "family_friendly", label: "Family Friendly", emoji: "👨‍👩‍👧‍👦" },
];

export const AGE_RANGES = ["18-24", "25-34", "35-44", "45-54", "55+"];
